<?php
echo '<html>';
echo '<head>';
echo '<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">';
echo '<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>';
echo '<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>';
echo '<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>';
echo '<script src="../static/js/main.js"></script>';
echo '</head>';
echo '<body>';
echo '<div id="page-wrapper" class="container my-5">';
echo '<div id="header" class="text-center">';
echo '<h1 class="mb-3">Image Background Changer</h1>';
echo '<h6>Change background of image using segmentation!</h6>';
echo '<a href="https://github.com/589hero/image-background-changer-demo" class="mr-5">GitHub</a>';
echo '<a href="https://ainize.ai/589hero/image-background-changer-demo">Ainize</a>';
echo '</div>';
echo '<hr class="my-3">';
echo '';
echo '<div id="explanation" class="text-center">';
echo '<h2 class="mb-3">How to use</h1>';
echo '<div class="text-left d-inline-flex">';
echo '<p>';
echo '1.&nbsp;&nbsp;Upload Original Image and Background Image.<br>';
echo '2.&nbsp;&nbsp;Press "Run" Button<br>';
echo '3.&nbsp;&nbsp;Check out the output image with changed background!<br>';
echo '</p>';
echo '</div>';
echo '</div>';
echo '<hr class="my-3">';
echo '';
echo '<div id="examples" class="text-center">';
echo '<h2 class="mb-3">Examples</h1>';
echo '<div id="example">';
echo '<figure style="display: inline-block;">';
echo '<img id="sample1-1" width="250" height="200" src="../static/images/animal-1.jpg">';
echo '</figure>';
echo '<figure style="display: inline-block;">';
echo '<img id="sample2-1" width="250" height="200" src="../static/images/forest-1.jpeg">';
echo '</figure>';
echo '<figure style="display: inline-block;">';
echo '<img id="sample3-1" width="250" height="200" src="../static/images/animal-1-out.png">';
echo '</figure>';
echo '</div>';
echo '<div id="example2">';
echo '<figure style="display: inline-block;">';
echo '<img id="sample1-2" width="250" height="200" src="../static/images/car-1.jpg">';
echo '<figcaption>Original Image</figcaption>';
echo '</figure>';
echo '<figure style="display: inline-block;">';
echo '<img id="sample2-2" width="250" height="200" src="../static/images/sky-1.jpeg">';
echo '<figcaption>Background Image</figcaption>';
echo '</figure>';
echo '<figure style="display: inline-block;">';
echo '<img id="sample3-2" width="250" height="200" src="../static/images/car-1-out.png">';
echo '<figcaption>Result Image</figcaption>';
echo '</figure>';
echo '</div>';
echo '</div>';
echo '<hr class="my-3">';
echo '';
echo '<div id="img-uploader" class="row justify-content-center">';
echo '<div id="org-img-contents" class="col-4 col-6-medium col-12-small text-center">';
echo '<section>';
echo '<h3>Original Image</h2>';
echo '<img id="org-img" class="mb-2" width="350" height="350" src="../static/images/thumbnail-1.jpeg">';
echo '<input type='file' id='org-img-input' onchange="setThumbnail(event, 'org-img');">';
echo '</section>';
echo '</div>';
echo '<div id="bg-img-contents" class="col-4 col-6-medium col-12-small text-center">';
echo '<section>';
echo '<h3>Background Image</h2>';
echo '<img id="bg-img" class="mb-2" width="350" height="350" src="../static/images/thumbnail-1.jpeg">';
echo '<input type='file' id='bg-img-input' onchange="setThumbnail(event, 'bg-img');">';
echo '</section>';
echo '</div>';
echo '</div>';
echo '<div class="my-5 text-center">';
echo '<button id="run" type='submit' class="btn btn-primary" style="margin-left: auto;" onclick="formSend();"> RUN </button>';
echo '</div>';
echo '<div class="text-center">';
echo '<h3>Result</h3>';
echo '<img id="result-img" style="display: inline-block;" width="500" height="350" src="../static/images/thumbnail-1.jpeg">';
echo '</div>';
echo '</div>';
echo '</body>';
echo '</html>';
?>
